apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-api
  labels:
    owner: ecominds
    app: dept-api
spec:
  selector:
    matchLabels:
      app: dept-api
  replicas: 1
  template:
    metadata:
      labels:
        app: dept-api
    spec:
      containers:
      - name: dept-api
        image: ecominds/dept-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    owner: ecominds
    app: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  replicas: 1
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: ecominds/user-service:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: ecominds.endpoint.dept-service.base-path
          value: http://dept-api-lb:8081/api/departments/
---     
apiVersion: v1
kind: Service
metadata:
  name: dept-api-lb
spec:
  selector:
    app: dept-api
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: LoadBalancer
---     
apiVersion: v1
kind: Service
metadata:
  name: user-api-lb
spec:
  selector:
    app: user-api
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8082
  type: LoadBalancer
