apiVersion: v1
kind: Service
metadata:
  name: dept-api-service
spec:
  selector:
    app: dept-api
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-api
spec:
  selector:
    matchLabels:
      app: dept-api
  replicas: 1
  template:
    metadata:
      labels:
        app: dept-api
    spec:
      containers:
      - name: dept-api
        image: ecominds/dept-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081